# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  vault-agent:
    image: hashicorp/vault:1.18
    container_name: vault-agent
    entrypoint:  /bin/sh -c "mkdir -p /etc/vault && vault agent -config=/etc/vault/vault-agent.hcl"
    environment:
      VAULT_ADDR: http://192.168.60.50:8200
    volumes:
      - ./vault-agent-config:/var/vault:rw
      - ./secrets:/vault/secrets/
    cap_add:
      - IPC_LOCK
    privileged: true
    restart: unless-stopped
    command: [ "agent", "-config=/var/vault/vault-agent.hcl" ]

  shop-auth:
    build:
      context: .
      target: final
    volumes:
      - ./secrets/auth-test/:/etc/env/
    ports:
      - 3000:3000
    depends_on:
      - vault-agent
  shop-inventory:
    build:
      context: .
      target: final
    volumes:
      - ./secrets/inventory-test/:/etc/env/
    ports:
      - 3001:3000
    depends_on:
      - vault-agent
  shop-item:
    build:
      context: .
      target: final
    volumes:
      - ./secrets/item-test/:/etc/env/
    ports:
      - 3002:3000
    depends_on:
      - vault-agent
  shop-payment:
    build:
      context: .
      target: final
    volumes:
      - ./secrets/payment-test/:/etc/env/
    ports:
      - 3003:3000
    depends_on:
      - vault-agent
  shop-player:
    build:
      context: .
      target: final
    volumes:
      - ./secrets/player-test/:/etc/env/
    ports:
      - 3004:3000
    depends_on:
      - vault-agent