# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  shop-auth:
    build:
      context: .
      target: final
    volumes:
      - ./env/test/auth/:/etc/env/
    ports:
      - 3000:3000
  shop-inventory:
    build:
      context: .
      target: final
    volumes:
      - ./env/test/inventory/:/etc/env/
    ports:
      - 3001:3000
  shop-item:
    build:
      context: .
      target: final
    volumes:
      - ./env/test/item/:/etc/env/
    ports:
      - 3002:3000
  shop-payment:
    build:
      context: .
      target: final
    volumes:
      - ./env/test/payment/:/etc/env/
    ports:
      - 3003:3000
  shop-player:
    build:
      context: .
      target: final
    volumes:
      - ./env/test/player/:/etc/env/
    ports:
      - 3004:3000