{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.httpRoute.nameRoute }}
  labels:
    {{ include "item-service.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- range .Values.httpRoute.parentRefs }}
    - name: {{ $.Values.gateway.nameGateway }}
      sectionName: {{ .sectionName }}
      kind: {{ .kind }}
    {{- end }}
  hostnames:
    {{- range .Values.httpRoute.hostnames }}
    - {{ . | quote }}
    {{- end }}
  rules:
    {{- range .Values.httpRoute.rules }}
    - matches:
        {{- range .matches }}
        - path:
            type: {{ .path.type }}
            value: {{ .path.value }}
        {{- end }}
      backendRefs:
        {{- range .backendRefs }}
        - name: {{ include "item-service.fullname" $}}
          port: {{ .port }}
        {{- end }}
      {{- if .filters }}
      filters:
        {{- range .filters }}
        - type: {{ .type }}
          requestRedirect:
            scheme: {{ .requestRedirect.scheme }}
        {{- end }}
      {{- end }}
    {{- end }}
{{- end }}
