{{- if .Values.ingress.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ include "auth-service.fullname" .}}
spec:
  controllerName: traefik.io/gateway-controller
{{- end -}}