{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.nameGateway }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}

  {{- with .Values.gateway.spec }}
  spec:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  # Only Routes from the same namespace are allowed.
  listeners:
    {{- range .Values.gateway.listeners }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      {{- if .tls }}
      tls:
        mode: {{ .tls.mode }}
        certificateRefs:
          {{- range .tls.certificateRefs }}
          - name: {{ .name }}
            namespace: {{ .namespace }}
          {{- end }}
      {{- end }}
      allowedRoutes:
        namespaces:
          from: {{ .allowedRoutes.namespaces.from }}
    {{- end }}
{{- end -}}
