{{- if .Values.ingress.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "auth-service.fullname" . }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ include "auth-service.fullname" . }}
      sectionName: http
      kind: Gateway
  hostnames:
  {{- range .Values.ingress.hosts }}
    - {{ .host | quote }}
  {{ end -}}
  rules:
    {{- range .Values.ingress.hosts }}
     - matches:
        {{- range .paths }}
        - path:
          {{- with .pathType }}
            type: {{ . }}
          {{- end }}
            value: {{ .path }}
        {{- end }}
       backendRefs:
        - name: {{ include "auth-service.fullname" $ }}
          port: {{ $.Values.service.port }}
    {{- end }}
{{- end }}