{{- if .Values.httpRoute.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sslSecret.nameSecret }}
type: kubernetes.io/tls
data:
  # Self-signed certificate for the whoami.localhost domain.
  tls.crt: | 
    {{ .Values.sslSecret.tls_crt }}
  tls.key: |
    {{ .Values.sslSecret.tls_key }}
{{- end }}