apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: shop-microservices
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/sekkarin/shop-microservices-argocd.git
        revision: HEAD
        files:
          - path: "applicationset/cluster-config/**/config.json"
  template:
    metadata:
      name: '{{cluster.basename}}'  # Adds a debug prefix 
    spec:
      project: "default"
      source:
        repoURL: '{{cluster.repoURL}}'
        chart: "{{cluster.chart}}"
        targetRevision: "{{cluster.version}}"
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{cluster.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
