apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/sekkarin/shop-microservice.git
        revision: HEAD
        directories:
          - path: "applicationset/cluster-config/auth-service/config.json"
  template:
    metadata:
      name: "debug-{{.basename}}"  # Adds a debug prefix
    spec:
      project: "default"
      source:
        repoURL: "{{.repoURL}}"
        chart: "{{.chart}}"
        targetRevision: "{{.version}}"
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "debug-{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
