apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/sekkarin/shop-microservice.git
        revision: HEAD
        directories:
          - path: "applicationset/cluster-config/auth-service/config.json"
  template:
    metadata:
      name: '{{ .basename }}'  # Fixed syntax
    spec:
      project: "{{ .namespace }}"
      source:
        repoURL: "{{ .repoURL }}"  # Corrected variable reference
        chart: "{{ .chart }}"
        targetRevision: "{{ .version }}"  # Dynamically fetches the latest version
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true