apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/sekkarin/shop-microservice.git
        revision: HEAD
        files:
          - path: "applicationset/cluster-config/auth-service/config.json"
  template:
    metadata:
      name: '{{ .basename | replace "." "-" }}'  # Converts dots to dashes
    spec:
      project: "default"
      source:
        repoURL: "https://{{ .repoURL }}"
        chart: "{{ .chart }}"
        targetRevision: "{{ .version }}"
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true